### ISSUE TITLE
Feature Request Discussion: Extract classes, compile CSS to local file

### ISSUE THREAD

**Issue by DavZim** [kylebutts/shiny.tailwind#4]
It would be great to be able to download the required CSS classes at run-app-time.
Eg a new function/option `use_tailwind(compile = TRUE)` which would:

1. go through all html, R, ... files and extracts classes at the time the app is run or deployed
2. fetch the classes from tailwindcss.com or some other place (haven't looked into this part yet, to be honest)
3. write the css to a file and include the css file in the UI part

This would mimik the tailwind CLI (https://tailwindcss.com/docs/installation).

This would allow offline use as well (or behind corporate proxies or the like).

Does this make sense to you? And do you have any idea how to implement step 2?

**Comment by kylebutts** [comment]
So, this is all pretty simple to do with the CLI. I did something like that here: https://github.com/kylebutts/tailwindr for RMarkdown files. Note it's pretty outdated but the idea is simple: do steps 3 and 4 [here](https://tailwindcss.com/docs/installation/using-postcss) using defaults if they aren't provided by the user. Then, run the node command that outputs to a css file. This is a bit less user-friendly since it requires users to have `node` and to install `tailwindcss` and it requires building the css anytime you update the code which could be a pain. 

I would think a separate function like `compile_css` that does this could be a nice addition to the package with proper documentation. Proper meaning (i) have how to install node and tailwindcss, (ii) describe the build step and the alternative which is the Play CDN (which can cause flashes since css is generated on the fly), (iii) describe the need to run the build step

**Comment by DavZim** [comment]
I wonder if its possible to do with plain R, ie without the need to install node or tailwindcss?

An alternative could be that you have a `download_full_css()` which downloads it to the install directory of the package, then on the `compile()` command, the respective CSS elements are extracted. That means the full 15something mb are downloaded once for the develop version, but then only the required CSS is needed in production.

However, I do not have the full picture of tailwind yet. It might be possible that this is only possible for a subset of its functionality. eg only base classes, maybe @apply, but maybe without custom colors and without plugins. Do you have more information on this?

**Comment by kylebutts** [comment]
https://tailwindcss.com/blog/standalone-cli.

Cool! There is an executable version that you can install that doesn't require `node`. We could have a function (obviously more complicated since there are different system requirements)

```r
install_tailwind <- function() {
  system(r"(
    curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-macos-arm64
    chmod +x tailwindcss-macos-arm64
    mv tailwindcss-macos-arm64 tailwindcss
  )")
}
```

Then, running it is easy with (
```r
system("./tailwindcss -i css/input.css -o css/output.css --minify")
```
where `input.css` just contains 
```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```
and `tailwind.config.js` should be located at the base folder
```js
module.exports = {
  content: ["./**/*.{html,js,R,Rmd}"],
  // ...
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
    require('@tailwindcss/line-clamp'),
    require('@tailwindcss/aspect-ratio'),
  ]
}
```

Of course, we can allow for customizations of these objects by the user and default to these if they don't supply those arguments.
